### ISSUE TITLE
Look into making these colorthief based

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/coreproject-v4-ui#82] opened 2024-05-21 02:11 UTC
![image](https://github.com/baseplate-admin/coreproject-v4-ui/assets/61817579/ea8d973d-7b72-4873-b484-37225c035bcf)
![image](https://github.com/baseplate-admin/coreproject-v4-ui/assets/61817579/1db36927-2cde-4817-9cdc-562c34427548)

**Comment by tokitouq** [comment] 2024-05-21 02:38
Duplicate of https://github.com/baseplate-admin/coreproject-v4-ui/issues/75

**Closed by tokitouq** 2024-05-21 02:38 UTC
